// mab-rental/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  imports: [],
  standalone: true,
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {
  currentYear: number = new Date().getFullYear();

}

<footer class="bg-gray-900 text-gray-400 pt-10 mt-10">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 justify-items-center">
            
            <div class="w-full">
                <h5 class="text-white text-xl font-semibold mb-4">Entre em contato</h5>
                <p class="mb-2 flex items-center">
                    <i class="fas fa-map-marker-alt mr-3 text-lg"></i>
                    Folha 17, Marabá - PA
                </p>
                <p class="mb-2 flex items-center">
                    <i class="fas fa-phone-alt mr-3 text-lg"></i>
                    (94) 99234-5678
                </p>
                <p class="mb-2 flex items-center">
                    <i class="fas fa-envelope mr-3 text-lg"></i>
                    AlugueAqui&#64;gmail.com
                </p>
                
                <div class="flex space-x-2 pt-4">
                    <a class="w-10 h-10 flex items-center justify-center rounded-full border border-gray-500 hover:border-white text-gray-400 hover:text-white transition duration-300" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="w-10 h-10 flex items-center justify-center rounded-full border border-gray-500 hover:border-white text-gray-400 hover:text-white transition duration-300" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="w-10 h-10 flex items-center justify-center rounded-full border border-gray-500 hover:border-white text-gray-400 hover:text-white transition duration-300" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                    <a class="w-10 h-10 flex items-center justify-center rounded-full border border-gray-500 hover:border-white text-gray-400 hover:text-white transition duration-300" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                </div>
            </div>
            
            <div class="w-full">
                <h5 class="text-white text-xl font-semibold mb-4">Links rápidos</h5>
                <a class="block text-gray-400 hover:text-white mb-2 transition duration-300" href="">&gt; Sobre nós</a>
                <a class="block text-gray-400 hover:text-white mb-2 transition duration-300" href="">&gt; Contatos</a>
                <a class="block text-gray-400 hover:text-white mb-2 transition duration-300" href="">&gt; Nossos serviços</a>
                <a class="block text-gray-400 hover:text-white mb-2 transition duration-300" href="">&gt; Política de Privacidade</a>
                <a class="block text-gray-400 hover:text-white mb-2 transition duration-300" href="">&gt; Termos e condições</a>
            </div>

            <div class="w-full">
                <h5 class="text-white text-xl font-semibold mb-4">Newsletter</h5>
                <p class="mb-4">Insira seu e-mail para ficar por dentro das novidades e receber mais informações!</p>
                
                <div class="relative">
                    <input 
                        class="form-control w-full p-3 pl-4 pr-16 bg-transparent border border-gray-600 rounded-lg focus:ring-blue-500 focus:border-blue-500 text-white placeholder-gray-500" 
                        type="email" 
                        placeholder="Seu e-mail"
                        required
                    >
                    <button 
                        type="button" 
                        class="absolute top-1 right-1 h-10 px-4 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition duration-300"
                        title="Inscreva-se"
                    >
                        Inscreva-se
                    </button>
                </div>
            </div>

             <div class="w-full hidden lg:block">
                </div>
        </div>
        
    </div>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 border-t border-gray-800 mt-8">
        <div class="text-center text-sm text-gray-500">
            &copy; {{ currentYear }} AlugueAqui. Todos os direitos reservados.
        </div>
    </div>
</footer>

// frontend/src/components/Footer.jsx
export const Footer = () => <div className="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
<div className="container py-5">
    <div className="row g-5 d-flex justify-content-around">
        <div className="col-lg-3 col-md-6">
            <h5 className="text-white mb-4">Entre em contato</h5>
            <p className="mb-2"><i className="fa fa-map-marker-alt me-3"></i>Folha 17, Marabá - PA</p>
            <p className="mb-2"><i className="fa fa-phone-alt me-3"></i>(94) 99234-5678</p>
            <p className="mb-2"><i className="fa fa-envelope me-3"></i>AlugueAqui@gmail.com</p>
            <div className="d-flex pt-2">
                <a className="btn btn-outline-light btn-social" href=""><i className="fab fa-twitter"></i></a>
                <a className="btn btn-outline-light btn-social" href=""><i className="fab fa-facebook-f"></i></a>
                <a className="btn btn-outline-light btn-social" href=""><i className="fab fa-youtube"></i></a>
                <a className="btn btn-outline-light btn-social" href=""><i className="fab fa-linkedin-in"></i></a>
            </div>
        </div>
        <div className="col-lg-3 col-md-6">
            <h5 className="text-white mb-4">Links rápidos</h5>
            <a className="btn btn-link text-white-50" href="">Sobre nós</a>
            <a className="btn btn-link text-white-50" href="">Contatos</a>
            <a className="btn btn-link text-white-50" href="">Nossos serviçoes</a>
            <a className="btn btn-link text-white-50" href="">Política de Privacidade</a>
            <a className="btn btn-link text-white-50" href="">Termos e condições</a>
        </div>
        <div className="col-lg-3 col-md-6">
            <h5 className="text-white mb-4">Newsletter</h5>
            <p>Insira seu e-mail para ficar por dentro das novidades e receber mais informações!</p>
            <div className="position-relative mx-auto" style={{maxWidth: "400px"}}>
                {/* <input className="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email"> */}
                <button type="button" className="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">Inscreva-se</button>
            </div>
        </div>
    </div>
</div>
</div>
