// mab-rental/src/app/components/nav-bar/nav-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common'; // Necessário para [ngClass] e lógica

@Component({
  selector: 'app-nav-bar',
  // SINTAXE MODERNA
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive], // Importações essenciais
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.css']
})
export class NavBarComponent implements OnInit {
  isAuthenticated: boolean = true;
  iconDeal: string = '/icon-deal.png';

  isMenuOpen: boolean = false;
  isImoveisDropdownOpen: boolean = false;
  isPaginasDropdownOpen: boolean = false;

  constructor(private router: Router) {}

  ngOnInit(): void {
    // Lógica de inicialização aqui
  }

  logout(): void {
    console.log('Usuário deslogado (Mock)');
    this.isAuthenticated = false;
    this.router.navigate(['/']);
  }

  handleAuthClick(): void {
    if (this.isAuthenticated) {
      this.logout();
    } else {
      this.router.navigate(['/login']);
    }
  }

  toggleMenu(): void {
    this.isMenuOpen = !this.isMenuOpen;
  }

  toggleImoveisDropdown(): void {
    this.isImoveisDropdownOpen = !this.isImoveisDropdownOpen;
    this.isPaginasDropdownOpen = false;
  }

  togglePaginasDropdown(): void {
    this.isPaginasDropdownOpen = !this.isPaginasDropdownOpen;
    this.isImoveisDropdownOpen = false;
  }
}
<nav class="bg-white shadow-md">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center h-20">

            <a routerLink="/" class="flex items-center text-center">
                <div class="icon p-2 mr-2 bg-gray-100 rounded-lg">
                    <img class="w-7 h-7 object-contain" [src]="iconDeal" alt="Icon" />
                </div>
                <h1 class="m-0 text-xl sm:text-2xl font-bold text-blue-600">Alugue Aqui</h1>
            </a>

            <div class="hidden lg:flex flex-1 justify-end items-center">
                <div class="flex space-x-4 mr-6 items-center">
                    
                    <a
                        (click)="handleAuthClick()"
                        [routerLink]="isAuthenticated ? null : '/login'"
                        class="text-gray-600 hover:text-blue-600 px-3 py-2 text-lg font-medium cursor-pointer transition duration-300"
                    >
                        {{ isAuthenticated ? 'Sair' : 'Login' }}
                    </a>

                    <a routerLink="/" routerLinkActive="text-blue-600 font-bold" [routerLinkActiveOptions]="{exact: true}"
                        class="text-gray-600 hover:text-blue-600 px-3 py-2 text-lg font-medium transition duration-300">
                        Início
                    </a>

                    <div class="relative group">
                        <button (click)="toggleImoveisDropdown()"
                            class="flex items-center text-gray-600 hover:text-blue-600 px-3 py-2 text-lg font-medium transition duration-300 focus:outline-none">
                            Imóveis <i class="fa fa-angle-down ml-1 text-sm"></i>
                        </button>
                        <div [class.hidden]="!isImoveisDropdownOpen"
                             class="absolute left-1/2 transform -translate-x-1/2 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-20 ring-1 ring-black ring-opacity-5 transition duration-300">
                            <a routerLink="/rentals" (click)="toggleImoveisDropdown()" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Lista de Imóveis</a>
                            <a routerLink="/types" (click)="toggleImoveisDropdown()" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Tipos de Imóveis</a>
                            <a routerLink="/agents" (click)="toggleImoveisDropdown()" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Corretores</a>
                        </div>
                    </div>

                    <div class="relative group">
                        <button (click)="togglePaginasDropdown()"
                            class="flex items-center text-gray-600 hover:text-blue-600 px-3 py-2 text-lg font-medium transition duration-300 focus:outline-none">
                            Páginas <i class="fa fa-angle-down ml-1 text-sm"></i>
                        </button>
                        <div [class.hidden]="!isPaginasDropdownOpen"
                             class="absolute left-1/2 transform -translate-x-1/2 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-20 ring-1 ring-black ring-opacity-5 transition duration-300">
                            <a routerLink="/testimonials" (click)="togglePaginasDropdown()" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Comentários</a>
                            <a routerLink="/404" (click)="togglePaginasDropdown()" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">404 Error</a>
                        </div>
                    </div>

                    <a routerLink="/contact" routerLinkActive="text-blue-600 font-bold"
                        class="text-gray-600 hover:text-blue-600 px-3 py-2 text-lg font-medium transition duration-300">
                        Contato
                    </a>
                </div>

                <a routerLink="/newrental"
                    class="hidden lg:inline-flex items-center bg-blue-600 text-white font-semibold py-3 px-6 rounded-lg hover:bg-blue-700 transition duration-300 ml-4">
                    Adicionar Imóvel
                </a>
            </div>

            <div class="lg:hidden">
                <button (click)="toggleMenu()" type="button" class="text-gray-500 hover:text-gray-700 focus:outline-none p-2 rounded-md">
                    <span class="sr-only">Abrir Menu</span>
                    @if (!isMenuOpen) {
                        <i class="fas fa-bars h-6 w-6"></i>
                    } @else {
                        <i class="fas fa-times h-6 w-6"></i>
                    }
                </button>
            </div>
        </div>
    </div>

    <div [class.hidden]="!isMenuOpen" class="lg:hidden border-t border-gray-100">
        <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
            <a (click)="handleAuthClick(); isMenuOpen = false" [routerLink]="isAuthenticated ? null : '/login'"
               class="block text-gray-600 hover:bg-gray-50 hover:text-blue-600 px-3 py-2 rounded-md text-base font-medium">
               {{ isAuthenticated ? 'Sair' : 'Login' }}
            </a>
            <a routerLink="/" (click)="isMenuOpen = false" class="block text-gray-600 hover:bg-gray-50 hover:text-blue-600 px-3 py-2 rounded-md text-base font-medium">Início</a>
            
            <a routerLink="/rentals" (click)="isMenuOpen = false" class="block text-gray-600 hover:bg-gray-50 hover:text-blue-600 px-3 py-2 rounded-md text-base font-medium">Lista de Imóveis</a>
            <a routerLink="/types" (click)="isMenuOpen = false" class="block text-gray-600 hover:bg-gray-50 hover:text-blue-600 px-3 py-2 rounded-md text-base font-medium">Tipos de Imóveis</a>
            <a routerLink="/agents" (click)="isMenuOpen = false" class="block text-gray-600 hover:bg-gray-50 hover:text-blue-600 px-3 py-2 rounded-md text-base font-medium">Corretores</a>
            <a routerLink="/testimonials" (click)="isMenuOpen = false" class="block text-gray-600 hover:bg-gray-50 hover:text-blue-600 px-3 py-2 rounded-md text-base font-medium">Comentários</a>
            <a routerLink="/contact" (click)="isMenuOpen = false" class="block text-gray-600 hover:bg-gray-50 hover:text-blue-600 px-3 py-2 rounded-md text-base font-medium">Contato</a>

            <a routerLink="/newrental" (click)="isMenuOpen = false"
                class="block bg-blue-600 text-white font-semibold py-2 px-3 rounded-lg hover:bg-blue-700 text-center mt-2">
                Adicionar Imóvel
            </a>
        </div>
    </div>
</nav>

// frontend/src/components/NavBar.jsx
import { NavLink } from "react-router"
import iconDeal from "../img/icon-deal.png"
import { useAuth } from "../auth/authContext"

export const NavBar = () => {

    const { isAuthenticated, logout } = useAuth()
    return <nav className="navbar navbar-expand-lg bg-white navbar-light py-0 px-4">
    <NavLink to="/" end className="navbar-brand d-flex align-items-center text-center">
        <div className="icon p-2 me-2">
            <img className="img-fluid" src={iconDeal} alt="Icon" style={{width: "30px", height: "30px"}}/>
        </div>
        <h1 className="m-0 text-primary">Alugue Aqui</h1>
    </NavLink>
    <button type="button" className="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarCollapse">
        <div className="navbar-nav ms-auto">
            <NavLink to={isAuthenticated ? "/" : "/login"} className="av-item nav-link" 
            onClick={()=>{
                isAuthenticated ? logout() : <Navigate to="/login" />
            }}>
                {isAuthenticated ? "Sair" : "Login"}
            </NavLink>
            <NavLink to="/" end className="nav-item nav-link active">Inicio</NavLink>
            <div className="nav-item dropdown">
                <NavLink to="#" className="nav-link dropdown-toggle" data-bs-toggle="dropdown">imoveis</NavLink>
                <div className="dropdown-menu rounded-0 m-0">
                    <NavLink to="/rentals" className="dropdown-item">Lista de imoveis</NavLink>
                    <NavLink to="/types" className="dropdown-item">Tipos de imoveis</NavLink>
                    <NavLink to="/agents" className="dropdown-item">Corretores</NavLink>
                </div>
            </div>
            <div className="nav-item dropdown">
                <NavLink to="#" className="nav-link dropdown-toggle" data-bs-toggle="dropdown">Paginas</NavLink>
                <div className="dropdown-menu rounded-0 m-0">
                    <NavLink to="/testimonials" className="dropdown-item">Comentarios</NavLink>
                    <NavLink to="/404" className="dropdown-item">404 Error</NavLink>
                </div>
            </div>
            <NavLink to="/contact" className="nav-item nav-link">Contato</NavLink>
        </div>
        <NavLink to="/newrental" className="btn btn-primary px-3 d-none d-lg-flex">Adicionar Imóvel</NavLink>
    </div>
</nav>
}
