// mab-rental/src/app/components/rental-list/rental-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

// Interface para tipagem dos dados do imóvel
interface Property {
  _id: number; // Mude de 'id' para '_id' para bater com o código original
  images: string[];
  status: string;
  type: string;
  price: string;
  title: string;
  location: string;
  sqft: string;
  bed: string;
  bath: string;
}

@Component({
  selector: 'app-rental-list',
  templateUrl: './rental-list.component.html',
  standalone: true,
  imports: [],
  styleUrls: ['./rental-list.component.css']
})
export class RentalListComponent implements OnInit {
  properties: Property[] = [];
  statusFilters: string[] = ["Todas", "Top", "Recentes"];
  activeStatus: string = "";
  
  // MOCK: Defina os dados mockados se a chamada real falhar ou para desenvolvimento
  private mockProperties: Property[] = [
    { _id: 1, images: ['assets/img/prop-1.jpg'], status: "Venda", type: "Casa", price: "500,000", title: "Casa de Campo Moderna", location: "São Paulo, SP", sqft: "200m²", bed: "3 Quartos", bath: "2 Banheiros" },
    { _id: 2, images: ['assets/img/prop-2.jpg'], status: "Aluguel", type: "Apartamento", price: "2.500", title: "Ap. com Varanda Gourmet", location: "Rio de Janeiro, RJ", sqft: "85m²", bed: "2 Quartos", bath: "1 Banheiro" },
    { _id: 3, images: ['assets/img/prop-3.jpg'], status: "Top", type: "Casa", price: "800,000", title: "Cobertura de Luxo", location: "Belo Horizonte, MG", sqft: "150m²", bed: "4 Quartos", bath: "3 Banheiros" },
    { _id: 4, images: ['assets/img/prop-4.jpg'], status: "Recentes", type: "Comercial", price: "4.000", title: "Escritório Novo", location: "Curitiba, PR", sqft: "50m²", bed: "0 Quartos", bath: "1 Banheiro" },
  ];

  constructor(private route: ActivatedRoute, private router: Router) {}

  ngOnInit(): void {
    // 1. Monitorar os parâmetros da URL para aplicar o filtro e definir o estado ativo
    this.route.queryParamMap.subscribe(params => {
      const statusOfList = params.get('status');
      this.activeStatus = statusOfList || ""; // Define o status ativo, vazio se não houver

      // 2. Carregar e filtrar os dados
      this.getAllRentals().then((data) => {
        // Implemente a lógica de filtragem simples aqui, baseada no `statusOfList`
        let filteredData = data;
        if (statusOfList && statusOfList !== "Todas") {
             // Lógica de filtragem real (Ex: filtrar por status)
             // filteredData = data.filter(p => p.status === statusOfList);
        }
        this.properties = filteredData;
      });
    });
  }

  // MOCK: Função para buscar os dados dos aluguéis (substitui userReq.getRentals())
  async getAllRentals(): Promise<Property[]> {
    console.log('Mock: Buscando todos os imóveis da API...');
    // No ambiente real, substitua por this.authService.getUser().getRentals();
    return new Promise(resolve => {
        setTimeout(() => resolve(this.mockProperties), 300); // Simula atraso da API
    });
  }

  // Função para mudar os parâmetros de filtro (usa o Router do Angular)
  changeFilterParams(newStatus: string): void {
    const statusParam = newStatus === 'Todas' ? null : newStatus;
    
    this.router.navigate([], {
        relativeTo: this.route,
        queryParams: { status: statusParam },
        queryParamsHandling: 'merge' // Mantém outros parâmetros da URL
    });
  }
}
<div class="py-12">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        <ul class="flex justify-center space-x-3 mb-8">
            <li *ngFor="let statusFilter of statusFilters; let index = index">
                <button
                    (click)="changeFilterParams(statusFilter)"
                    [ngClass]="{
                        'bg-blue-600 text-white shadow-md': (activeStatus === statusFilter || (statusFilter === 'Todas' && !activeStatus)),
                        'border border-blue-600 text-blue-600 hover:bg-blue-50': !(activeStatus === statusFilter || (statusFilter === 'Todas' && !activeStatus))
                    }"
                    class="py-2 px-5 rounded-lg font-semibold transition duration-300"
                >
                    {{ statusFilter }}
                </button>
            </li>
        </ul>

        <div *ngIf="properties.length === 0" class="text-center p-10 bg-gray-50 rounded-lg">
            <h1 class="text-3xl font-bold mb-3 text-gray-800">Sem Imóveis Disponíveis</h1>
            <p class="text-gray-600">Ainda não temos imóveis que correspondem aos critérios da sua busca.</p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div *ngFor="let property of properties; let index = index" class="animate-fade-in">
                
                <div class="bg-white rounded-xl shadow-lg hover:shadow-xl transition duration-300 overflow-hidden">
                    
                    <div class="relative overflow-hidden h-64">
                        <a [routerLink]="['/rental', property._id]">
                            <img class="w-full h-full object-cover transform hover:scale-105 transition duration-500" 
                                 [src]="property.images[0]" 
                                 [alt]="property.title" />
                        </a>
                        
                        <div class="bg-blue-600 rounded text-white absolute top-4 left-4 py-1 px-3 text-sm font-medium shadow-md">
                            {{ property.status }}
                        </div>
                        
                        <div class="bg-white rounded-t-lg text-blue-600 absolute bottom-0 left-4 mx-4 pt-1 px-3 text-sm font-medium shadow-md">
                            {{ property.type }}
                        </div>
                    </div>

                    <div class="p-5 pb-0">
                        <h5 class="text-blue-600 mb-3 text-2xl font-bold">R$ {{ property.price }}</h5>
                        
                        <a class="block text-xl font-semibold mb-2 text-gray-800 hover:text-blue-600 transition duration-300" 
                           [routerLink]="['/rental', property._id]">
                            {{ property.title }}
                        </a>
                        
                        <p class="text-gray-500 text-sm">
                            <i class="fa fa-map-marker-alt text-blue-600 mr-2"></i>
                            {{ property.location }}
                        </p>
                    </div>

                    <div class="flex border-t border-gray-100 mt-4 divide-x divide-gray-100 text-sm text-gray-600">
                        
                        <small class="flex-1 text-center py-3">
                            <i class="fa fa-ruler-combined text-blue-600 mr-2"></i>
                            {{ property.sqft }}
                        </small>
                        
                        <small class="flex-1 text-center py-3">
                            <i class="fa fa-bed text-blue-600 mr-2"></i>
                            {{ property.bed }}
                        </small>
                        
                        <small class="flex-1 text-center py-3">
                            <i class="fa fa-bath text-blue-600 mr-2"></i>
                            {{ property.bath }}
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// frontend/src/components/RentalList.jsx
import React, { useEffect, useState } from 'react';
import { NavLink } from 'react-router';
import { useAuth } from '../auth/authContext';

export const RentalList = () => {
    const [properties, setProperties] = useState([]); // Estado para armazenar as propriedades
    const [statusFilters, setStatusFilters] = useState(["Todas", "Top", "Recentes"]); // Filtros de status
    const [activeStatus, setActiveStatus] = useState(""); // Estado para o filtro ativo

    const { getUser } = useAuth()
    const userReq = getUser()
    // Função para buscar os dados das propriedades
    const getAllRentals = async () => {
        const data = await userReq.getRentals()
        return data
        /* return [
            {
                id: 1,
                imgSrc: ["https://silver-umbrella-jjpxpp7rgvrhq776-5173.app.github.dev/public/5-1.jpg"],
                status: "Venda",
                type: "Casa",
                price: "500,000",
                title: "Casa com 3 quartos",
                location: "São Paulo, SP",
                sqft: "200m²",
                bed: "3 Quartos",
                bath: "2 Banheiros",
            },
            // Adicione mais propriedades aqui...
        ]; */
    };

    // Função para mudar os parâmetros de filtro
    const changeFilterParams = (newStatus) => {
        const url = new URL(window.location.href);
        url.searchParams.set('status', newStatus === 'Todas' ? "" : newStatus);
        window.location.href = url;
    };

    // Efeito para carregar os dados ao montar o componente
    useEffect(() => {
        const urlParams = new URLSearchParams(window.location.search);
        const statusOfList = urlParams.get('status');
        const typeOfList = urlParams.get('type');
        const sectorOfList = urlParams.get('sector');

        setActiveStatus(statusOfList || "");

        getAllRentals().then((data) => {
            console.log(data)
            setProperties(data);
        });
    }, []);

    return (
        <div>
            {/* Filtros de status */}
            <ul id="filter-list" className="nav nav-pills mb-4">
                {statusFilters.map((statusFilter, index) => (
                    <li key={index} className="nav-item me-2">
                        <button
                            className={`btn btn-outline-primary ${activeStatus === statusFilter ? "active" : ""}`}
                            onClick={() => changeFilterParams(statusFilter)}
                        >
                            {statusFilter}
                        </button>
                    </li>
                ))}
            </ul>

            {/* Título da lista de propriedades */}
            {properties.length === 0 && (
                <div id="property-list-title" className="text-center">
                    <h1 className="mb-3">Sem Imóveis Disponíveis</h1>
                    <p>Ainda não temos imóveis que correspondem aos critérios da sua busca.</p>
                </div>
            )}

            {/* Lista de propriedades */}
            <div id="property-list" className="row">
                {properties.map((property, index) => {
                    const delay = 0.1 + index * 0.2; // Ajusta o delay da animação
                    return (
                        <div key={property._id} className="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay={`${delay}s`}>
                            <div className="property-item rounded overflow-hidden">
                                <div className="position-relative overflow-hidden">
                                    <NavLink to={`/rental/${property._id}`}>
                                        <img className="img-fluid image-lista" src={property.images[0]} alt={property.title} />
                                    </NavLink>
                                    <div className="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">
                                        {property.status}
                                    </div>
                                    <div className="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">
                                        {property.type}
                                    </div>
                                </div>
                                <div className="p-4 pb-0">
                                    <h5 className="text-primary mb-3">R$ {property.price}</h5>
                                    
                                    <NavLink className="d-block h5 mb-2" to={`rental/${property._id}`}>
                                        {property.title}
                                    </NavLink>
                                    <p>
                                        <i className="fa fa-map-marker-alt text-primary me-2"></i>
                                        {property.location}
                                    </p>
                                </div>
                                <div className="d-flex border-top">
                                    <small className="flex-fill text-center border-end py-2">
                                        <i className="fa fa-ruler-combined text-primary me-2"></i>
                                        {property.sqft}
                                    </small>
                                    <small className="flex-fill text-center border-end py-2">
                                        <i className="fa fa-bed text-primary me-2"></i>
                                        {property.bed}
                                    </small>
                                    <small className="flex-fill text-center py-2">
                                        <i className="fa fa-bath text-primary me-2"></i>
                                        {property.bath}
                                    </small>
                                </div>
                            </div>
                        </div>
                    );
                })}
            </div>
        </div>
    );
};
