// mab-rental/src/app/components/search-rental/search-rental.component.ts
import { Component, signal, inject, Input } from '@angular/core';
import { CommonModule, DOCUMENT } from '@angular/common';
import { FormsModule } from '@angular/forms'; // Necessário para ngModel

@Component({
  selector: 'app-search-rental',
  standalone: true, // Implementação moderna do Angular
  imports: [CommonModule, FormsModule], // Importa módulos necessários para ngFor e ngModel
  templateUrl: './search-rental.component.html',
  styleUrl: './search-rental.component.css'
})
export class SearchRentalComponent {
  // 1. Injeção segura do objeto 'window' via DOCUMENT
  private document = inject(DOCUMENT);
  
  // 2. Estado (React useState -> Angular signal)
  // Usamos signals para reatividade moderna e tipagem estrita
  @Input('propertyType') propertyType!: string
  @Input('location') location!: string

  // 3. Dados para os dropdowns (Arrays)
  readonly propertyTypes = [
    'Casa', 'Apartamento', 'Comercial', 'Germinada', 
    'Predio', 'Escritorio', 'Garagem', 'Residencial'
  ];

  readonly locations = [
    'Nova Marabá', 'Velha Marabá', 'Cidade Nova', 'Cidade Jardim', 'São Felix'
  ];

  /**
   * Função para lidar com o clique no botão de busca.
   * Navega para a página de listagem, adicionando os parâmetros de busca na URL.
   */
  handleSearch(): void {
    // Acessa o objeto window de forma segura
    const window = this.document.defaultView; 
    
    if (!window) {
      console.error("Ambiente de navegador não detectado.");
      return;
    }

    // Cria a URL com os valores atuais
    const url = new URL(window.location.href);
    
    // Configura o novo caminho
    url.pathname = "/property-list.html"; 
    
    // Adiciona os parâmetros de busca (os valores atuais dos signals)
    url.searchParams.set('type', this.propertyType);
    url.searchParams.set('sector', this.location);

    // Redireciona o usuário
    window.location.href = url.toString();
  }
}

<div class="row g-2 d-flex justify-content-around">
    <div class="col-md-10">
        <div class="row g-2">
            
            <div class="col-md-4">
                <select
                    class="form-select border-0 py-3"
                    #typeSelect="ngModel"
                    
                    [(ngModel)]="propertyType" 
                >
                    <option value="">Tipo de propriedade</option>
                    
                    @for (type of propertyTypes; track type) {
                        <option [value]="type">
                            {{ type }}
                        </option>
                    }
                </select>
            </div>

            <div class="col-md-4">
                <select
                    class="form-select border-0 py-3"
                    #locationSelect="ngModel"
                    
                    [(ngModel)]="location"
                >
                    <option value="">Localização</option>
                    
                    @for (loc of locations; track loc) {
                        <option [value]="loc">
                            {{ loc }}
                        </option>
                    }
                </select>
            </div>
            
        </div>
    </div>

    <div class="col-md-2">
        <button
            class="btn btn-dark border-0 w-100 py-3"
            
            (click)="handleSearch()"
        >
            Procurar
        </button>
    </div>
</div>

// frontend/src/components/SearchRental.jsx
import React, { useState } from 'react';

export const SearchRental = () => {
    // Estados para armazenar os valores dos selects
    const [propertyType, setPropertyType] = useState('');
    const [location, setLocation] = useState('');

    // Função para lidar com o clique no botão de busca
    const handleSearch = () => {
        const url = new URL(window.location.href);
        url.pathname = "/property-list.html"; // Altere para o caminho correto
        url.searchParams.set('type', propertyType);
        url.searchParams.set('sector', location);
        window.location.href = url;
    };

    return (
        <div className="row g-2 d-flex justify-content-around">
            {/* Coluna dos inputs */}
            <div className="col-md-10">
                <div className="row g-2">
                    {/* Select do tipo de propriedade */}
                    <div className="col-md-4">
                        <select
                            className="form-select border-0 py-3"
                            value={propertyType}
                            onChange={(e) => setPropertyType(e.target.value)}
                        >
                            <option value="">Tipo de propriedade</option>
                            {["Casa", "Apartamento", "Comercial", "Germinada", "Predio", "Escritorio", "Garagem", "Residencial"].map((type, index) => (
                                <option key={index} value={type}>
                                    {type}
                                </option>
                            ))}
                        </select>
                    </div>

                    {/* Select da localização */}
                    <div className="col-md-4">
                        <select
                            className="form-select border-0 py-3"
                            value={location}
                            onChange={(e) => setLocation(e.target.value)}
                        >
                            <option value="">Localização</option>
                            {["Nova Marabá", "Velha Marabá", "Cidade Nova", "Cidade Jardim", "São Felix"].map((loc, index) => (
                                <option key={index} value={loc}>
                                    {loc}
                                </option>
                            ))}
                        </select>
                    </div>
                </div>
            </div>

            {/* Coluna do botão de busca */}
            <div className="col-md-2">
                <button
                    className="btn btn-dark border-0 w-100 py-3"
                    onClick={handleSearch}
                >
                    Procurar
                </button>
            </div>
        </div>
    );
};
