// frontend/src/components/RentalTypes.jsx
import React, { useEffect, useState } from 'react';

import house  from "../img/icon-house.png"
import villa from "../img/icon-villa.png"
import apartment from "../img/icon-apartment.png"
import housing from "../img/icon-housing.png"
import building from "../img/icon-building.png"
import neighborhood from "../img/icon-neighborhood.png"
import luxury from "../img/icon-luxury.png"
import condominium from "../img/icon-condominium.png"

export const RentalTypes = () => {
    const [data, setData] = useState([]); // Estado para armazenar os dados das propriedades

    // Simulação da função getAllRentals (substitua pela sua lógica de fetch)
    const getAllRentals = async () => {
        // Exemplo de dados simulados
        return [
            { type: "Casa" },
            { type: "Apartamento" },
            { type: "Residencial" },
            { type: "Escritorio" },
            { type: "Prédio" },
            { type: "Germinada" },
            { type: "Garagem" },
            { type: "Comercial" },
        ];
    };

    // Efeito para carregar os dados ao montar o componente
    useEffect(() => {
        getAllRentals().then((response) => {
            setData(response);
        });
    }, []);

    // Dados dos tipos de propriedade
    const propertyTypes = [
        { name: "Casa", imgSrc: house },
        { name: "Residencial", imgSrc: villa },
        { name: "Apartamento", imgSrc: apartment },
        { name: "Escritorio", imgSrc: housing },
        { name: "Prédio", imgSrc: building },
        { name: "Germinada", imgSrc: neighborhood },
        { name: "Garagem", imgSrc: luxury },
        { name: "Comercial", imgSrc: condominium },
    ];

    // Função para gerar a URL com o tipo de propriedade
    const generateUrl = (type) => {
        const url = new URL(window.location.href);
        url.pathname = "/property-list.html"; // Altere para o caminho correto
        url.searchParams.set('type', type);
        return url.toString();
    };

    return (
        <div id="com-propstypes">
            {/* Título e descrição */}
            <div className="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style={{ maxWidth: "600px" }}>
                <h1 className="mb-3">Tipos de Propriedade</h1>
                <p>
                    De apartamentos modernos a casas espaçosas, oferecemos uma variedade de imóveis para aluguel que atendem às suas necessidades. Explore nossas opções e descubra o lugar ideal para chamar de lar.
                </p>
            </div>

            {/* Lista de tipos de propriedade */}
            <div className="row g-4">
                {propertyTypes.map((propsType, index) => (
                    <div key={index} className="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <a className="cat-item d-block bg-light text-center rounded p-3" href={generateUrl(propsType.name)}>
                            <div className="rounded p-4">
                                <div className="icon mb-3">
                                    <img className="img-fluid" src={propsType.imgSrc} alt="Icon" />
                                </div>
                                <h6>{propsType.name}</h6>
                                <span>
                                    {data.filter((prop) => prop.type === propsType.name).length} propriedades
                                </span>
                            </div>
                        </a>
                    </div>
                ))}
            </div>
        </div>
    );
};

// mab-rental/src/app/components/rental-types/rental-types.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

// Interface para um item de propriedade simplificado (apenas o tipo é necessário para a contagem)
interface Property {
  type: string;
}

// Interface para um item de tipo de propriedade com ícone
interface PropertyType {
  name: string;
  imgSrc: string;
}

@Component({
  selector: 'app-rental-types',
  standalone: true,
  imports: [],
  templateUrl: './rental-types.component.html',
  styleUrls: ['./rental-types.component.css']
})
export class RentalTypesComponent implements OnInit {
  // Lista de todas as propriedades carregadas (mockada)
  propertiesData: Property[] = [];
  
  // Dados dos tipos de propriedade com caminhos de imagem
  propertyTypes: PropertyType[] = [
    { name: "Casa", imgSrc: 'assets/img/icon-house.png' },
    { name: "Residencial", imgSrc: 'assets/img/icon-villa.png' },
    { name: "Apartamento", imgSrc: 'assets/img/icon-apartment.png' },
    { name: "Escritorio", imgSrc: 'assets/img/icon-housing.png' },
    { name: "Prédio", imgSrc: 'assets/img/icon-building.png' },
    { name: "Germinada", imgSrc: 'assets/img/icon-neighborhood.png' },
    { name: "Garagem", imgSrc: 'assets/img/icon-luxury.png' },
    { name: "Comercial", imgSrc: 'assets/img/icon-condominium.png' },
  ];

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.getAllRentals().then((response) => {
      this.propertiesData = response;
    });
  }

  // MOCK: Simulação da função de busca de todas as propriedades
  async getAllRentals(): Promise<Property[]> {
    console.log('Mock: Buscando todos os tipos de imóveis...');
    // Dados simulados que viriam da sua API para contagem
    return new Promise(resolve => {
        setTimeout(() => resolve([
            { type: "Casa" },
            { type: "Apartamento" },
            { type: "Apartamento" },
            { type: "Residencial" },
            { type: "Escritorio" },
            { type: "Prédio" },
            { type: "Germinada" },
            { type: "Garagem" },
            { type: "Comercial" },
            { type: "Casa" },
        ]), 100); 
    });
  }

  // Função para contar as propriedades por tipo
  countPropertiesByType(typeName: string): number {
    return this.propertiesData.filter((prop) => prop.type === typeName).length;
  }

  // Função para gerar a URL com o tipo de propriedade (navegação no Angular)
  navigateToPropertyList(type: string): void {
    // Redireciona para a lista de propriedades com o parâmetro de query 'type'
    this.router.navigate(['/property-list'], { queryParams: { type: type } });
  }
}
<div class="py-12">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div class="text-center mx-auto mb-12" style="max-width: 600px;">
            <h2 class="text-3xl sm:text-4xl font-bold mb-3 text-gray-800 animate-fade-in-down">
                Tipos de Propriedade
            </h2>
            <p class="text-gray-600">
                De apartamentos modernos a casas espaçosas, oferecemos uma variedade de imóveis para aluguel que atendem às suas necessidades. Explore nossas opções e descubra o lugar ideal para chamar de lar.
            </p>
        </div>

        <div class="grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-4 lg:gap-8">
            <div *ngFor="let propsType of propertyTypes; let index = index">
                
                <a (click)="navigateToPropertyList(propsType.name)"
                   class="cursor-pointer group block bg-gray-50 text-center rounded-xl p-4 sm:p-6 transition duration-300 transform hover:scale-105 hover:shadow-xl">
                    
                    <div class="p-4 sm:p-6">
                        <div class="mb-3 flex justify-center">
                            <img class="w-12 h-12 object-contain filter group-hover:invert-0 transition duration-300" 
                                 [src]="propsType.imgSrc" 
                                 [alt]="'Ícone de ' + propsType.name" />
                        </div>
                        
                        <h6 class="text-xl font-semibold mb-2 text-gray-800 group-hover:text-blue-600 transition duration-300">
                            {{ propsType.name }}
                        </h6>
                        
                        <span class="text-sm text-gray-500">
                            {{ countPropertiesByType(propsType.name) }} propriedades
                        </span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
