// frontend/src/components/RentalInfo.jsx
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router'; // Importe useParams
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/swiper-bundle.css'; // Estilos do Swiper
import SwiperCore from 'swiper'
import { Navigation, Pagination, Autoplay } from 'swiper/modules';
import { useAuth } from '../auth/authContext';
console.log(Autoplay)
// Inicializa os módulos do Swiper
SwiperCore.use([Navigation, Pagination, Autoplay]);

export const RentalInfo = () => {
  const [rental, setRental] = useState(null);
  const [images, setImages] = useState([]);

  // Captura o parâmetro "id" da URL
  const { id } = useParams();

  // Função para buscar os dados do aluguel pelo ID
  const { getUser } = useAuth()
  const userReq = getUser()
   


  // Efeito para carregar os dados do aluguel
  useEffect(() => {
    if (id) {
      userReq.getOneRental(id).then((rentalData) => {
        setRental(rentalData);
        setImages(rentalData.images);
      });
    }
  }, [id]); // Executa sempre que o "id" mudar

  return (
    <div className="container-xxl py-5">
      <div className="container">
        <div className="row g-5 align-items-center">
          {/* Carrossel de Imagens com Swiper */}
          <div className="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
            <div className="about-img position-relative overflow-hidden p-5 pe-0">
              <div className="col-md-15 animated fadeIn">
                <Swiper
                  navigation
                  pagination={{ clickable: true }}
                  autoplay={{ delay: 3000 }}
                  loop
                  className="header-carousel"
                >
                  {images.map((imageSrc, index) => (
                    <SwiperSlide key={index}>
                      <img
                        className="image-lista-carrossel w-100"
                        src={imageSrc}
                        alt={`Imagem ${index + 1}`}
                      />
                    </SwiperSlide>
                  ))}
                </Swiper>
              </div>
            </div>
          </div>

          {/* Detalhes do Aluguel */}
          <div className="col-lg-6 wow fadeIn" data-wow-delay="0.5s" id="com-detalhe">
            {rental ? (
              <>
                <h1 className="mb-4">{rental.title}</h1>
                <p className="mb-4">{rental.description || ""}</p>
                <p><i className="fa fa-cart-plus text-primary me-3"></i>R$ {rental.price}</p>
                <p><i className="fa fa-map text-primary me-3"></i>{rental.location}</p>
                <p><i className="fa fa-map-pin text-primary me-3"></i>Setor {rental.sector}</p>
                <p><i className="fa fa-ruler-combined text-primary me-3"></i>{rental.sqft} mt²</p>
                <p><i className="fa fa-bed text-primary me-3"></i>{rental.bed} quartos</p>
                <p><i className="fa fa-bath text-primary me-3"></i>{rental.bath} banheiros</p>
                <a className="btn btn-primary py-3 px-5 mt-3" href="">Fale com o proprietário</a>
              </>
            ) : (
              <p>Carregando...</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

// mab-rental/src/app/components/rental-info/rental-info.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import Swiper from 'swiper';
import { SwiperOptions } from 'swiper/types';
import { Navigation, Pagination, Autoplay } from 'swiper/modules';

// Defina a interface para o objeto de aluguel para tipagem segura
interface Rental {
  id: string;
  title: string;
  description: string;
  price: number;
  location: string;
  sector: string;
  sqft: number;
  bed: number;
  bath: number;
  images: string[];
}

@Component({
  selector: 'app-rental-info',
  standalone: true,
  templateUrl: './rental-info.component.html',
  styleUrls: ['./rental-info.component.css'],
})
export class RentalInfoComponent implements OnInit {
  rental: Rental | null = null;
  images: string[] = [];
  rentalId: string | null = null;
  
  // Configuração do Swiper para o Angular
  swiperConfig: SwiperOptions = {
    modules: [Navigation, Pagination, Autoplay],
    navigation: true,
    pagination: { clickable: true },
    autoplay: { delay: 3000, disableOnInteraction: false },
    loop: true,
    slidesPerView: 1,
    spaceBetween: 0,
  };

  // Injete o ActivatedRoute para obter o parâmetro da URL
  constructor(private route: ActivatedRoute) {
    // Registra os módulos do Swiper (necessário para que a navegação e paginação funcionem)
    Swiper.use([Navigation, Pagination, Autoplay]);
  }

  ngOnInit(): void {
    // Obtém o 'id' da URL
    this.route.paramMap.subscribe(params => {
      this.rentalId = params.get('id');
      if (this.rentalId) {
        this.loadRentalData(this.rentalId);
      }
    });
  }

  // MOCK: Simula a função de busca do imóvel (Substitua pela lógica do seu serviço de Auth/API)
  loadRentalData(id: string): void {
    console.log(`Buscando imóvel com ID: ${id}`);
    
    // Simulação dos dados que viriam da API
    const mockRentalData: Rental = {
      id: id,
      title: 'Apartamento de Luxo com Vista Panorâmica',
      description: 'Este é um lindo apartamento, perfeito para quem busca conforto e modernidade no centro da cidade.',
      price: 3500.00,
      location: 'Rua Principal, 123',
      sector: 'Centro',
      sqft: 85,
      bed: 2,
      bath: 2,
      images: [
        'assets/img/rental-1.jpg', // Adicione caminhos reais
        'assets/img/rental-2.jpg',
        'assets/img/rental-3.jpg',
        'assets/img/rental-4.jpg',
      ],
    };

    // Simula um atraso de rede
    setTimeout(() => {
      this.rental = mockRentalData;
      this.images = mockRentalData.images;
    }, 500);
  }

  // Função para formatar o preço (opcional, mas recomendado)
  formatPrice(price: number): string {
    return price.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
  }
}
<div class="py-12">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div *ngIf="rental; else loadingTemplate" class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
            
            <div class="animate-fade-in-slow">
                <div class="relative overflow-hidden rounded-xl shadow-2xl">
                    
                    <swiper [config]="swiperConfig" class="w-full h-full">
                        <ng-template swiperSlide *ngFor="let imageSrc of images; let i = index">
                            <img
                                class="w-full h-96 object-cover"
                                [src]="imageSrc"
                                [alt]="'Imagem do Imóvel ' + (i + 1)"
                            />
                        </ng-template>
                    </swiper>
                    
                </div>
            </div>

            <div class="animate-fade-in-slow">
                <h1 class="text-3xl sm:text-4xl font-bold mb-4 text-gray-900">{{ rental.title }}</h1>
                <p class="mb-6 text-gray-600 leading-relaxed">{{ rental.description }}</p>

                <div class="space-y-3 text-lg">
                    <p class="flex items-center text-gray-800">
                        <i class="fa fa-cart-plus text-xl text-blue-600 mr-4 w-6 text-center"></i>
                        <span class="font-semibold text-blue-600">{{ formatPrice(rental.price) }}</span>
                    </p>
                    <p class="flex items-center text-gray-700">
                        <i class="fa fa-map-marker-alt text-xl text-blue-600 mr-4 w-6 text-center"></i>
                        {{ rental.location }}
                    </p>
                    <p class="flex items-center text-gray-700">
                        <i class="fa fa-map-pin text-xl text-blue-600 mr-4 w-6 text-center"></i>
                        Setor {{ rental.sector }}
                    </p>
                    <p class="flex items-center text-gray-700">
                        <i class="fa fa-ruler-combined text-xl text-blue-600 mr-4 w-6 text-center"></i>
                        {{ rental.sqft }} m²
                    </p>
                    <p class="flex items-center text-gray-700">
                        <i class="fa fa-bed text-xl text-blue-600 mr-4 w-6 text-center"></i>
                        {{ rental.bed }} quartos
                    </p>
                    <p class="flex items-center text-gray-700">
                        <i class="fa fa-bath text-xl text-blue-600 mr-4 w-6 text-center"></i>
                        {{ rental.bath }} banheiros
                    </p>
                </div>

                <a href="tel:PROPRIETARIO" 
                   class="inline-block mt-8 bg-blue-600 text-white font-semibold py-3 px-6 rounded-lg hover:bg-blue-700 transition duration-300 shadow-md">
                    Fale com o proprietário
                </a>
            </div>

        </div>

        <ng-template #loadingTemplate>
            <div class="text-center p-10">
                <p class="text-xl text-gray-500">Carregando detalhes do imóvel...</p>
                <div class="mt-4 animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600 mx-auto"></div>
            </div>
        </ng-template>
    </div>
</div>
