// mab-rental/src/app/components/add-rental/add-rental.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CommonModule, NgClass } from '@angular/common';

@Component({
  selector: 'app-add-rental',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule, NgClass], 
  templateUrl: './add-rental.component.html',
  styleUrls: ['./add-rental.component.css']
})
export class AddRentalComponent implements OnInit {
  addRentalForm!: FormGroup;
  isSubmitting: boolean = false;

  statusOptions = ["Recentes", "Venda", "Aluguel"];
  typeOptions = ["Casa", "Apartamento", "Terreno"];

  constructor(private fb: FormBuilder, private router: Router) {}

  ngOnInit(): void {
    // Inicializa o formulário reativo
    this.addRentalForm = this.fb.group({
      status: ['', Validators.required],
      type: ['', Validators.required],
      price: ['', [Validators.required, Validators.pattern(/^[0-9,.]+$/)]],
      title: ['', Validators.required],
      location: ['', Validators.required],
      sector: ['', Validators.required],
      sqft: ['', [Validators.required, Validators.pattern(/^[0-9]+$/)]],
      bed: ['', [Validators.required, Validators.min(0)]],
      bath: ['', [Validators.required, Validators.min(0)]],
      contact: ['', Validators.required],
      images: [null, Validators.required]
    });
  }

  get f() {
    return this.addRentalForm.controls;
  }

  // MOCK: Simula a chamada userReq.createRental()
  async mockCreateRental(data: any): Promise<{ success: boolean; error?: any }> {
    console.log('Mock: Tentativa de cadastro do imóvel:', data);
    return new Promise(resolve => {
      setTimeout(() => {
        if (Math.random() > 0.1) {
          resolve({ success: true });
        } else {
          resolve({ success: false, error: 'Erro de rede simulado' });
        }
      }, 1000);
    });
  }

  async onSubmit(): Promise<void> {
    this.isSubmitting = true;

    if (this.addRentalForm.invalid) {
      this.addRentalForm.markAllAsTouched();
      this.isSubmitting = false;
      return;
    }
    
    const dataToSend = this.addRentalForm.value;

    try {
      await this.mockCreateRental(dataToSend);
      alert('Imóvel cadastrado com sucesso! ✅');
      this.addRentalForm.reset();
      this.router.navigate(['/']);
    } catch (error) {
      alert('Erro ao cadastrar imóvel. Tente novamente.');
    } finally {
      this.isSubmitting = false;
    }
  }
}
<div class="py-12">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mx-auto mb-8" style="max-width: 600px;">
            <h1 class="text-3xl sm:text-4xl font-bold mb-3 text-gray-800 animate-fade-in-down">Cadastrar Imóvel</h1>
            <p class="text-gray-600">Preencha os detalhes do imóvel que deseja cadastrar.</p>
        </div>

        <form [formGroup]="addRentalForm" (ngSubmit)="onSubmit()" class="mx-auto max-w-4xl bg-white p-8 rounded-xl shadow-2xl">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                <div class="relative">
                    <select
                        formControlName="status"
                        id="status"
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-600 appearance-none"
                        [ngClass]="{ 'border-red-500': f['status'].invalid && (f['status'].dirty || f['status'].touched) }"
                    >
                        <option value="" disabled selected>Selecione o status</option>
                        
                        @for (status of statusOptions; track status) {
                            <option [value]="status">{{ status }}</option>
                        }
                    </select>
                    <label htmlFor="status" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all">Status</label>
                    
                    @if (f['status'].invalid && (f['status'].dirty || f['status'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['status'].errors?.['required']) {
                                <p>Status é obrigatório</p>
                            }
                        </div>
                    }
                </div>

                <div class="relative">
                    <select
                        formControlName="type"
                        id="type"
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-600 appearance-none"
                        [ngClass]="{ 'border-red-500': f['type'].invalid && (f['type'].dirty || f['type'].touched) }"
                    >
                        <option value="" disabled selected>Selecione o tipo</option>
                        
                        @for (type of typeOptions; track type) {
                            <option [value]="type">{{ type }}</option>
                        }
                    </select>
                    <label htmlFor="type" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all">Tipo</label>
                    
                    @if (f['type'].invalid && (f['type'].dirty || f['type'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['type'].errors?.['required']) {
                                <p>Tipo é obrigatório</p>
                            }
                        </div>
                    }
                </div>
                
                <div class="relative">
                    <input type="text" formControlName="price" id="price" placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{ 'border-red-500 focus:ring-red-500': f['price'].invalid && (f['price'].dirty || f['price'].touched) }"
                    />
                    <label htmlFor="price" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Preço</label>
                    
                    @if (f['price'].invalid && (f['price'].dirty || f['price'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['price'].errors?.['required']) {
                                <p>Preço é obrigatório</p>
                            }
                        </div>
                    }
                </div>

                <div class="relative">
                    <input type="text" formControlName="title" id="title" placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{ 'border-red-500 focus:ring-red-500': f['title'].invalid && (f['title'].dirty || f['title'].touched) }"
                    />
                    <label htmlFor="title" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Título</label>
                    
                    @if (f['title'].invalid && (f['title'].dirty || f['title'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['title'].errors?.['required']) {
                                <p>Título é obrigatório</p>
                            }
                        </div>
                    }
                </div>
                
                <div class="relative">
                    <input type="text" formControlName="location" id="location" placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{ 'border-red-500 focus:ring-red-500': f['location'].invalid && (f['location'].dirty || f['location'].touched) }"
                    />
                    <label htmlFor="location" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Localização</label>
                    
                    @if (f['location'].invalid && (f['location'].dirty || f['location'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['location'].errors?.['required']) {
                                <p>Localização é obrigatória</p>
                            }
                        </div>
                    }
                </div>

                <div class="relative">
                    <input type="text" formControlName="sector" id="sector" placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{ 'border-red-500 focus:ring-red-500': f['sector'].invalid && (f['sector'].dirty || f['sector'].touched) }"
                    />
                    <label htmlFor="sector" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Setor</label>
                    
                    @if (f['sector'].invalid && (f['sector'].dirty || f['sector'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['sector'].errors?.['required']) {
                                <p>Setor é obrigatório</p>
                            }
                        </div>
                    }
                </div>
                
                <div class="relative">
                    <input type="text" formControlName="sqft" id="sqft" placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{ 'border-red-500 focus:ring-red-500': f['sqft'].invalid && (f['sqft'].dirty || f['sqft'].touched) }"
                    />
                    <label htmlFor="sqft" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Área (m²)</label>
                    
                    @if (f['sqft'].invalid && (f['sqft'].dirty || f['sqft'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['sqft'].errors?.['required']) {
                                <p>Área é obrigatória</p>
                            }
                        </div>
                    }
                </div>
                
                <div class="relative">
                    <input type="text" formControlName="bed" id="bed" placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{ 'border-red-500 focus:ring-red-500': f['bed'].invalid && (f['bed'].dirty || f['bed'].touched) }"
                    />
                    <label htmlFor="bed" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Quartos</label>
                    
                    @if (f['bed'].invalid && (f['bed'].dirty || f['bed'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['bed'].errors?.['required']) {
                                <p>Quartos são obrigatórios</p>
                            }
                        </div>
                    }
                </div>

                <div class="relative">
                    <input type="text" formControlName="bath" id="bath" placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{ 'border-red-500 focus:ring-red-500': f['bath'].invalid && (f['bath'].dirty || f['bath'].touched) }"
                    />
                    <label htmlFor="bath" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Banheiros</label>
                    
                    @if (f['bath'].invalid && (f['bath'].dirty || f['bath'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['bath'].errors?.['required']) {
                                <p>Banheiros são obrigatórios</p>
                            }
                        </div>
                    }
                </div>
                
                <div class="relative">
                    <input type="text" formControlName="contact" id="contact" placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{ 'border-red-500 focus:ring-red-500': f['contact'].invalid && (f['contact'].dirty || f['contact'].touched) }"
                    />
                    <label htmlFor="contact" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Contato</label>
                    
                    @if (f['contact'].invalid && (f['contact'].dirty || f['contact'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['contact'].errors?.['required']) {
                                <p>Contato é obrigatório</p>
                            }
                        </div>
                    }
                </div>

                <div class="md:col-span-2 relative">
                    <label htmlFor="images" class="block text-sm font-medium text-gray-700 mb-1">Imagens (Múltiplas)</label>
                    <input
                        type="file"
                        formControlName="images"
                        id="images"
                        multiple
                        class="w-full border border-gray-300 rounded-lg p-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-600"
                        [ngClass]="{ 'border-red-500': f['images'].invalid && (f['images'].dirty || f['images'].touched) }"
                    />
                    
                    @if (f['images'].invalid && (f['images'].dirty || f['images'].touched)) {
                        <div class="mt-1 text-sm text-red-500">
                            @if (f['images'].errors?.['required']) {
                                <p>Imagens são obrigatórias</p>
                            }
                        </div>
                    }
                </div>

                <div class="md:col-span-2 mt-4">
                    <button 
                        type="submit" 
                        [disabled]="addRentalForm.invalid || isSubmitting"
                        class="w-full bg-blue-600 text-white font-semibold py-3 rounded-lg hover:bg-blue-700 transition duration-300 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {{ isSubmitting ? 'Cadastrando...' : 'Cadastrar Imóvel' }}
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

// frontend/src/pages/AddRental.jsx
import React from 'react';
import { useForm } from 'react-hook-form';
import { useAuth } from '../auth/authContext';
import { Navigate } from 'react-router';

export const AddRental = () => {
  const { register, handleSubmit, formState: { errors }, reset } = useForm();
  const { getUser } = useAuth()
  const userReq = getUser()
  const onSubmit = async (data) => {
    console.log('Dados do imóvel:', data);
    try {
      await userReq.createRental(data);
      alert('Imóvel cadastrado com sucesso!');
      reset(); // Limpa o formulário após o envio
      <Navigate to="/" />
    } catch (error) {
      alert('Erro ao cadastrar imóvel. Tente novamente.');
    }
  }
  return (
    <div className="container-xxl py-5">
      <div className="container">
        <div className="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style={{ maxWidth: '600px' }}>
          <h1 className="mb-3">Cadastrar Imóvel</h1>
          <p>Preencha os detalhes do imóvel que deseja cadastrar.</p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="wow fadeInUp" data-wow-delay="0.3s">
          <div className="row g-3">
            {/* Status */}
            <div className="col-md-6">
              <div className="form-floating">
                <select
                  className={`form-control ${errors.status ? 'is-invalid' : ''}`}
                  id="status"
                  {...register('status', { required: 'Status é obrigatório' })}
                >
                  <option value="">Selecione o status</option>
                  <option value="Recentes">Recentes</option>
                  <option value="Venda">Venda</option>
                  <option value="Aluguel">Aluguel</option>
                </select>
                <label htmlFor="status">Status</label>
                {errors.status && (
                  <div className="invalid-feedback">{errors.status.message}</div>
                )}
              </div>
            </div>

            {/* Tipo */}
            <div className="col-md-6">
              <div className="form-floating">
                <select
                  className={`form-control ${errors.type ? 'is-invalid' : ''}`}
                  id="type"
                  {...register('type', { required: 'Tipo é obrigatório' })}
                >
                  <option value="">Selecione o tipo</option>
                  <option value="Casa">Casa</option>
                  <option value="Apartamento">Apartamento</option>
                  <option value="Terreno">Terreno</option>
                </select>
                <label htmlFor="type">Tipo</label>
                {errors.type && (
                  <div className="invalid-feedback">{errors.type.message}</div>
                )}
              </div>
            </div>

            {/* Preço */}
            <div className="col-md-6">
              <div className="form-floating">
                <input
                  type="text"
                  className={`form-control ${errors.price ? 'is-invalid' : ''}`}
                  id="price"
                  placeholder="Preço"
                  {...register('price', { required: 'Preço é obrigatório' })}
                />
                <label htmlFor="price">Preço</label>
                {errors.price && (
                  <div className="invalid-feedback">{errors.price.message}</div>
                )}
              </div>
            </div>

            {/* Título */}
            <div className="col-md-6">
              <div className="form-floating">
                <input
                  type="text"
                  className={`form-control ${errors.title ? 'is-invalid' : ''}`}
                  id="title"
                  placeholder="Título"
                  {...register('title', { required: 'Título é obrigatório' })}
                />
                <label htmlFor="title">Título</label>
                {errors.title && (
                  <div className="invalid-feedback">{errors.title.message}</div>
                )}
              </div>
            </div>

            {/* Localização */}
            <div className="col-md-6">
              <div className="form-floating">
                <input
                  type="text"
                  className={`form-control ${errors.location ? 'is-invalid' : ''}`}
                  id="location"
                  placeholder="Localização"
                  {...register('location', { required: 'Localização é obrigatória' })}
                />
                <label htmlFor="location">Localização</label>
                {errors.location && (
                  <div className="invalid-feedback">{errors.location.message}</div>
                )}
              </div>
            </div>

            {/* Setor */}
            <div className="col-md-6">
              <div className="form-floating">
                <input
                  type="text"
                  className={`form-control ${errors.sector ? 'is-invalid' : ''}`}
                  id="sector"
                  placeholder="Setor"
                  {...register('sector', { required: 'Setor é obrigatório' })}
                />
                <label htmlFor="sector">Setor</label>
                {errors.sector && (
                  <div className="invalid-feedback">{errors.sector.message}</div>
                )}
              </div>
            </div>

            {/* Área (m²) */}
            <div className="col-md-6">
              <div className="form-floating">
                <input
                  type="text"
                  className={`form-control ${errors.sqft ? 'is-invalid' : ''}`}
                  id="sqft"
                  placeholder="Área (m²)"
                  {...register('sqft', { required: 'Área é obrigatória' })}
                />
                <label htmlFor="sqft">Área (m²)</label>
                {errors.sqft && (
                  <div className="invalid-feedback">{errors.sqft.message}</div>
                )}
              </div>
            </div>

            {/* Quartos */}
            <div className="col-md-6">
              <div className="form-floating">
                <input
                  type="text"
                  className={`form-control ${errors.bed ? 'is-invalid' : ''}`}
                  id="bed"
                  placeholder="Quartos"
                  {...register('bed', { required: 'Número de quartos é obrigatório' })}
                />
                <label htmlFor="bed">Quartos</label>
                {errors.bed && (
                  <div className="invalid-feedback">{errors.bed.message}</div>
                )}
              </div>
            </div>

            {/* Banheiros */}
            <div className="col-md-6">
              <div className="form-floating">
                <input
                  type="text"
                  className={`form-control ${errors.bath ? 'is-invalid' : ''}`}
                  id="bath"
                  placeholder="Banheiros"
                  {...register('bath', { required: 'Número de banheiros é obrigatório' })}
                />
                <label htmlFor="bath">Banheiros</label>
                {errors.bath && (
                  <div className="invalid-feedback">{errors.bath.message}</div>
                )}
              </div>
            </div>

            {/* Contato */}
            <div className="col-md-6">
              <div className="form-floating">
                <input
                  type="text"
                  className={`form-control ${errors.contact ? 'is-invalid' : ''}`}
                  id="contact"
                  placeholder="Contato"
                  {...register('contact', { required: 'Contato é obrigatório' })}
                />
                <label htmlFor="contact">Contato</label>
                {errors.contact && (
                  <div className="invalid-feedback">{errors.contact.message}</div>
                )}
              </div>
            </div>

            <div className="col-md-12">
              <div className="form-floating">
                <input
                  type="file"
                  className={`form-control ${errors.images ? 'is-invalid' : ''}`}
                  id="images"
                  multiple
                  {...register('images', { required: 'Imagens são obrigatórias' })}
                />
                <label htmlFor="images">Imagens</label>
                {errors.images && (
                  <div className="invalid-feedback">{errors.images.message}</div>
                )}
              </div>
            </div>

            {/* Botão de Envio */}
            <div className="col-12">
              <button className="btn btn-primary w-100 py-3" type="submit">
                Cadastrar Imóvel
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};
