// mab-rental/src/app/components/agents/agents.component.ts
import { Component, OnInit } from '@angular/core';
import { CtaComponent } from '../cta/cta.component';

interface Agent {
  fullName: string;
  designation: string;
  imageSrc: string;
  facebookUrl: string;
  instagramUrl: string;
  linkedInUrl: string;
}

@Component({
  selector: 'app-agents',
  imports: [CtaComponent],
  templateUrl: './agents.component.html',
  styleUrls: ['./agents.component.css']
})
export class AgentsComponent implements OnInit {

  // Lista de agentes com caminhos de imagem atualizados para 'assets/'
  agents: Agent[] = [
    {
      fullName: "Ricardo Diniz",
      designation: "Corretor",
      imageSrc: "assets/img/team-rdm.jpg",
      facebookUrl: "",
      instagramUrl: "",
      linkedInUrl: "",
    },
    {
      fullName: "Winy Soares",
      designation: "Corretor",
      imageSrc: "assets/img/team-winy.jpg",
      facebookUrl: "",
      instagramUrl: "",
      linkedInUrl: "",
    },
    {
      fullName: "Ruan Vieira",
      designation: "Corretor",
      imageSrc: "assets/img/team-ruan.png",
      facebookUrl: "",
      instagramUrl: "",
      linkedInUrl: "",
    },
  ];

  constructor() { }

  ngOnInit(): void {
    // Aqui você faria a chamada à API para carregar a lista de corretores
    // Ex: this.agentService.loadAgents().subscribe(data => this.agents = data);
  }
}
<div class="py-12 sm:py-16">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div class="text-center mx-auto mb-12" style="max-width: 600px;">
            <h2 class="text-3xl sm:text-4xl font-bold mb-3 text-gray-800 animate-fade-in-down">
                Corretores
            </h2>
            <p class="text-gray-600">
                Nossos corretores são profissionais dedicados, prontos para oferecer suporte e guiar você na escolha do imóvel ideal, tornando o processo de aluguel mais fácil e seguro.
            </p>
        </div>
        
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8 justify-items-center">
            
            <div *ngFor="let agent of agents" class="w-full max-w-sm animate-fade-in">
                <div class="bg-white rounded-xl shadow-lg overflow-hidden transition duration-300 transform hover:scale-[1.02]">
                    <div class="relative overflow-hidden">
                        <img class="w-full h-auto object-cover" [src]="agent.imageSrc" [alt]="agent.fullName"/>
                        
                        <div class="absolute left-1/2 bottom-0 flex justify-center transform -translate-x-1/2 translate-y-1/2">
                            <div class="flex space-x-2 bg-white p-2 rounded-full shadow-lg border border-gray-100">
                                <a *ngIf="agent.facebookUrl" 
                                   class="w-10 h-10 flex items-center justify-center rounded-full bg-blue-600 text-white hover:bg-blue-700 transition duration-300" 
                                   [href]="agent.facebookUrl" target="_blank">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                                <a *ngIf="agent.instagramUrl" 
                                   class="w-10 h-10 flex items-center justify-center rounded-full bg-blue-600 text-white hover:bg-blue-700 transition duration-300" 
                                   [href]="agent.instagramUrl" target="_blank">
                                    <i class="fab fa-instagram"></i>
                                </a>
                                <a *ngIf="agent.linkedInUrl" 
                                   class="w-10 h-10 flex items-center justify-center rounded-full bg-blue-600 text-white hover:bg-blue-700 transition duration-300" 
                                   [href]="agent.linkedInUrl" target="_blank">
                                    <i class="fab fa-linkedin-in"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    
                    <div class="text-center p-4 pt-12">
                        <h5 class="text-xl font-bold mb-0 text-gray-800">{{ agent.fullName }}</h5>
                        <small class="text-gray-500">{{ agent.designation }}</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<hr class="border-gray-100 my-8">

<app-cta></app-cta>

// frontend/src/pages/Agents.jsx
import React from 'react';
import { CallAction } from "../components/CallAction";

export const Agents = () => {
  const agents = [
    {
      fullName: "Ricardo Diniz",
      designation: "Corretor",
      imageSrc: "img/team-rdm.jpg",
      facebookUrl: "",
      instagramUrl: "",
      linkedInUrl: "",
    },
    {
      fullName: "Winy Soares",
      designation: "Corretor",
      imageSrc: "img/team-winy.jpg",
      facebookUrl: "",
      instagramUrl: "",
      linkedInUrl: "",
    },
    {
      fullName: "Ruan Vieira",
      designation: "Corretor",
      imageSrc: "img/team-ruan.png",
      facebookUrl: "",
      instagramUrl: "",
      linkedInUrl: "",
    },
  ];

  // Função para gerar o card de cada corretor
  const generatePropertyAgent = (agent) => (
    <div className="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s" key={agent.fullName}>
      <div className="team-item rounded overflow-hidden">
        <div className="position-relative">
          <img className="img-fluid" src={agent.imageSrc} alt={agent.fullName} />
          <div className="position-absolute start-50 top-100 translate-middle d-flex align-items-center">
            {agent.facebookUrl && (
              <a className="btn btn-square mx-1" href={agent.facebookUrl} target="_blank" rel="noopener noreferrer">
                <i className="fab fa-facebook-f"></i>
              </a>
            )}
            {agent.instagramUrl && (
              <a className="btn btn-square mx-1" href={agent.instagramUrl} target="_blank" rel="noopener noreferrer">
                <i className="fab fa-instagram"></i>
              </a>
            )}
            {agent.linkedInUrl && (
              <a className="btn btn-square mx-1" href={agent.linkedInUrl} target="_blank" rel="noopener noreferrer">
                <i className="fab fa-linkedin-in"></i>
              </a>
            )}
          </div>
        </div>
        <div className="text-center p-4 mt-3">
          <h5 className="fw-bold mb-0">{agent.fullName}</h5>
          <small>{agent.designation}</small>
        </div>
      </div>
    </div>
  );

  return<><div className="container-xxl py-5">     
        <div className="container" id="com-corretores">
            <div className="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style={{ maxWidth: '600px' }}>
                <h1 className="mb-3">Corretores</h1>
                <p>
                    Nossos corretores são profissionais dedicados, prontos para oferecer suporte e guiar você na escolha do imóvel ideal, tornando o processo de aluguel mais fácil e seguro.
                </p>
            </div>
            <div className="row g-4 justify-content-center">
                {agents.map((agent) => generatePropertyAgent(agent))}
            </div>
        </div>
    </div>
    <CallAction/>
    </> 
};
