// mab-rental/src/app/pages/contact/contact.component.ts
// ContactComponent.ts (Permanece o mesmo)

import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common'; 
import { Router, RouterLink } from '@angular/router'; // Adicionando RouterLink para uso no template

@Component({
  selector: 'app-contact',
  standalone: true,
  // Mantemos CommonModule e ReactiveFormsModule para a validação e pipes
  imports: [CommonModule, ReactiveFormsModule], 
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css']
})
export class ContactComponent implements OnInit {
  contactForm!: FormGroup;
  isSubmitting: boolean = false;
  
  // Dados estáticos de contato
  contactInfo = [
    { iconClass: 'fa-map-marker-alt', label: 'Endereço', value: 'Folha 17, Marabá - PA', delay: '0.1s' },
    { iconClass: 'fa-envelope-open', label: 'Email', value: 'AlugueAqui@gmail.com', delay: '0.3s' },
    { iconClass: 'fa-phone-alt', label: 'Telefone', value: '(94) 99234-5678', delay: '0.5s' },
  ];

  constructor(private fb: FormBuilder, private router: Router) {}

  ngOnInit(): void {
    // Inicializa o formulário reativo
    this.contactForm = this.fb.group({
      name: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      subject: ['', Validators.required],
      message: ['', Validators.required],
    });
  }

  // Getter para acesso fácil aos controles
  get f() {
    return this.contactForm.controls;
  }

  onSubmit(): void {
    this.isSubmitting = true;
    
    if (this.contactForm.invalid) {
      this.contactForm.markAllAsTouched();
      this.isSubmitting = false;
      return;
    }

    console.log('Dados do formulário de contato:', this.contactForm.value);
    
    // Simular envio de API
    setTimeout(() => {
      alert('Mensagem enviada com sucesso! Em breve retornaremos o contato.');
      this.contactForm.reset();
      this.isSubmitting = false;
    }, 1500);
  }
}
<div class="py-12 sm:py-16">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div class="text-center mx-auto mb-12" style="max-width: 600px;">
            <h1 class="text-3xl sm:text-4xl font-bold mb-3 text-gray-800 animate-fade-in-down">Nossos contatos</h1>
            <p class="text-gray-600">
                Entre em contato conosco para esclarecer suas dúvidas ou solicitar nossos serviços. Estamos sempre disponíveis para oferecer o melhor atendimento possível para você!
            </p>
        </div>

        <div class="grid grid-cols-1 gap-10">
            
            <div class="col-span-full">
                <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                    
                    @for (item of contactInfo; track item.label) {
                        <div class="animate-fade-in">
                            <div class="bg-gray-100 rounded-lg p-3">
                                <div 
                                    class="flex items-center bg-white rounded-lg p-3 border border-dashed border-teal-500/30"
                                    style="--tw-border-opacity: 0.3;"
                                >
                                    <div class="flex items-center justify-center w-12 h-12 mr-3 rounded-full bg-blue-50 text-blue-600">
                                        <i class="fa text-xl" [ngClass]="'fa-' + item.iconClass"></i>
                                    </div>
                                    <div class="flex flex-col">
                                        <span class="text-sm text-gray-500 font-medium">{{ item.label }}</span>
                                        <span class="text-gray-800 font-semibold">{{ item.value }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

            <div class="grid grid-cols-1 lg:grid-cols-2 gap-10">
                
                <div class="animate-fade-in">
                    <iframe
                        class="w-full rounded-xl shadow-lg"
                        src="https://maps.google.com/maps?q=Marabá,+Pará&t=&z=13&ie=UTF8&iwloc=&output=embed"
                        frameBorder="0"
                        style="min-height: 400px; border: 0;"
                        allowFullScreen
                        aria-hidden="false"
                        tabIndex="0"
                        title="Mapa de localização"
                    ></iframe>
                </div>

                <div class="animate-fade-in">
                    <p class="mb-6 text-gray-600">
                        Preencha o formulário abaixo para entrar em contato conosco. Envie suas dúvidas, sugestões ou solicite mais informações sobre as casas disponíveis para alugar. Nossa equipe receberá sua mensagem por e-mail e retornará o mais breve possível!
                    </p>
                    
                    <form [formGroup]="contactForm" (ngSubmit)="onSubmit()">
                        <div class="grid grid-cols-1 sm:grid-cols-2 gap-6">
                            
                            <div class="relative">
                                <input type="text" formControlName="name" id="name" placeholder=" "
                                    class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                                    [ngClass]="{ 'border-red-500 focus:ring-red-500': f['name'].invalid && (f['name'].dirty || f['name'].touched) }"
                                />
                                <label htmlFor="name" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Seu nome</label>
                                
                                @if (f['name'].invalid && (f['name'].dirty || f['name'].touched)) {
                                    <div class="mt-1 text-sm text-red-500">
                                        @if (f['name'].errors?.['required']) {
                                            <p>O nome é obrigatório.</p>
                                        }
                                    </div>
                                }
                            </div>

                            <div class="relative">
                                <input type="email" formControlName="email" id="email" placeholder=" "
                                    class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                                    [ngClass]="{ 'border-red-500 focus:ring-red-500': f['email'].invalid && (f['email'].dirty || f['email'].touched) }"
                                />
                                <label htmlFor="email" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Seu email</label>
                                
                                @if (f['email'].invalid && (f['email'].dirty || f['email'].touched)) {
                                    <div class="mt-1 text-sm text-red-500">
                                        @if (f['email'].errors?.['required']) {
                                            <p>O email é obrigatório.</p>
                                        }
                                        @if (f['email'].errors?.['email']) {
                                            <p>O email é inválido.</p>
                                        }
                                    </div>
                                }
                            </div>

                            <div class="sm:col-span-2 relative">
                                <input type="text" formControlName="subject" id="subject" placeholder=" "
                                    class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                                    [ngClass]="{ 'border-red-500 focus:ring-red-500': f['subject'].invalid && (f['subject'].dirty || f['subject'].touched) }"
                                />
                                <label htmlFor="subject" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Título da mensagem</label>
                                
                                @if (f['subject'].invalid && (f['subject'].dirty || f['subject'].touched)) {
                                    <div class="mt-1 text-sm text-red-500">
                                        @if (f['subject'].errors?.['required']) {
                                            <p>O título é obrigatório.</p>
                                        }
                                    </div>
                                }
                            </div>

                            <div class="sm:col-span-2 relative">
                                <textarea formControlName="message" id="message" placeholder=" "
                                    class="w-full h-36 px-4 py-3 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                                    [ngClass]="{ 'border-red-500 focus:ring-red-500': f['message'].invalid && (f['message'].dirty || f['message'].touched) }"
                                ></textarea>
                                <label htmlFor="message" class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm">Mensagem</label>
                                
                                @if (f['message'].invalid && (f['message'].dirty || f['message'].touched)) {
                                    <div class="mt-1 text-sm text-red-500">
                                        @if (f['message'].errors?.['required']) {
                                            <p>A mensagem é obrigatória.</p>
                                        }
                                    </div>
                                }
                            </div>

                            <div class="sm:col-span-2">
                                <button 
                                    type="submit" 
                                    [disabled]="contactForm.invalid || isSubmitting"
                                    class="w-full bg-blue-600 text-white font-semibold py-3 rounded-lg hover:bg-blue-700 transition duration-300 disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {{ isSubmitting ? 'Enviando...' : 'Enviar mensagem' }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

// frontend/src/pages/Contact.jsx
import React from 'react';

export const Contact = () => {
  return (
    <div className="container-xxl py-5">
      <div className="container">
        {/* Título e descrição */}
        <div className="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style={{ maxWidth: '600px' }}>
          <h1 className="mb-3">Nossos contatos</h1>
          <p>
            Entre em contato conosco para esclarecer suas dúvidas ou solicitar nossos serviços. Estamos sempre disponíveis para oferecer o melhor atendimento possível para você!
          </p>
        </div>

        {/* Cards de contato */}
        <div className="row g-4">
          <div className="col-12">
            <div className="row gy-4">
              {/* Endereço */}
              <div className="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="0.1s">
                <div className="bg-light rounded p-3">
                  <div className="d-flex align-items-center bg-white rounded p-3" style={{ border: '1px dashed rgba(0, 185, 142, .3)' }}>
                    <div className="icon me-3" style={{ width: '45px', height: '45px' }}>
                      <i className="fa fa-map-marker-alt text-primary"></i>
                    </div>
                    <span>Folha 17, Marabá - PA</span>
                  </div>
                </div>
              </div>

              {/* Email */}
              <div className="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="0.3s">
                <div className="bg-light rounded p-3">
                  <div className="d-flex align-items-center bg-white rounded p-3" style={{ border: '1px dashed rgba(0, 185, 142, .3)' }}>
                    <div className="icon me-3" style={{ width: '45px', height: '45px' }}>
                      <i className="fa fa-envelope-open text-primary"></i>
                    </div>
                    <span>AlugueAqui@gmail.com</span>
                  </div>
                </div>
              </div>

              {/* Telefone */}
              <div className="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="0.5s">
                <div className="bg-light rounded p-3">
                  <div className="d-flex align-items-center bg-white rounded p-3" style={{ border: '1px dashed rgba(0, 185, 142, .3)' }}>
                    <div className="icon me-3" style={{ width: '45px', height: '45px' }}>
                      <i className="fa fa-phone-alt text-primary"></i>
                    </div>
                    <span>(94) 99234-5678</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Mapa */}
          <div className="col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <iframe
              className="position-relative rounded w-100 h-100"
              src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15845.745616624137!2d-49.110762!3d-5.368759!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x92bdb4d86e891a27%3A0x0!2zTWVldGluZyBvZiB0aGUgUml2ZXM!5e0!3m2!1spt-BR!2sbr!4v1695228900000!5m2!1spt-BR!2sbr"
              frameBorder="0"
              style={{ minHeight: '400px', border: '0' }}
              allowFullScreen
              aria-hidden="false"
              tabIndex="0"
              title="Mapa de localização"
            ></iframe>
          </div>

          {/* Formulário de contato */}
          <div className="col-md-6">
            <div className="wow fadeInUp" data-wow-delay="0.5s">
              <p className="mb-4">
                Preencha o formulário abaixo para entrar em contato conosco. Envie suas dúvidas, sugestões ou solicite mais informações sobre as casas disponíveis para alugar. Nossa equipe receberá sua mensagem por e-mail e retornará o mais breve possível!
              </p>
              <form>
                <div className="row g-3">
                  {/* Nome */}
                  <div className="col-md-6">
                    <div className="form-floating">
                      <input type="text" className="form-control" id="name" placeholder="Your Name" />
                      <label htmlFor="name">Seu nome</label>
                    </div>
                  </div>

                  {/* Email */}
                  <div className="col-md-6">
                    <div className="form-floating">
                      <input type="email" className="form-control" id="email" placeholder="Your Email" />
                      <label htmlFor="email">Seu email</label>
                    </div>
                  </div>

                  {/* Assunto */}
                  <div className="col-12">
                    <div className="form-floating">
                      <input type="text" className="form-control" id="subject" placeholder="Subject" />
                      <label htmlFor="subject">Título da mensagem</label>
                    </div>
                  </div>

                  {/* Mensagem */}
                  <div className="col-12">
                    <div className="form-floating">
                      <textarea
                        className="form-control"
                        placeholder="Leave a message here"
                        id="message"
                        style={{ height: '150px' }}
                      ></textarea>
                      <label htmlFor="message">Mensagem</label>
                    </div>
                  </div>

                  {/* Botão de envio */}
                  <div className="col-12">
                    <button className="btn btn-primary w-100 py-3" type="submit">
                      Enviar mensagem
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
