// mab-rental/src/app/pages/rental-list-page/rental-list-page.component.ts
import { Component } from '@angular/core';
import { CtaComponent } from '../../components/cta/cta.component';
import { RentalListComponent } from '../../components/rental-list/rental-list.component';

@Component({
  selector: 'app-rental-list-page',
  standalone: true,
  imports: [CtaComponent, RentalListComponent],
  templateUrl: './rental-list-page.component.html',
  styleUrl: './rental-list-page.component.css'
})
export class RentalListPageComponent {
  constructor() { }
  
  ngOnInit(): void {}
}

<div>
    <div class="py-12 sm:py-16">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="grid grid-cols-1 lg:grid-cols-3 gap-8 items-end mb-10">
                
                <div class="lg:col-span-2">
                    <div class="text-left mx-auto">
                        <h2 class="text-3xl sm:text-4xl font-bold mb-3 text-gray-800 animate-slide-in-left">
                            Imóveis Disponíveis
                        </h2>
                        <p class="text-gray-600">
                            Explore nossa seleção de imóveis disponíveis para aluguel e encontre o lar perfeito para você. Cada opção é cuidadosamente selecionada para atender às suas necessidades e estilo de vida.
                        </p>
                    </div>
                </div>
                
                <div class="hidden lg:block">
                    </div>
            </div>
            
            <div>
                <app-rental-list></app-rental-list>
                
                <div class="col-span-full text-center mt-10">
                    <a routerLink="/rentals"
                       class="inline-block bg-blue-600 text-white font-semibold py-3 px-8 rounded-lg hover:bg-blue-700 transition duration-300 shadow-md">
                        Mostrar mais Imóveis
                    </a>
                </div>
            </div>
        </div>
    </div>
    
    <app-cta></app-cta>
</div>

// frontend/src/pages/RentalListPage.jsx
import { RentalList } from '../components/RentalList'
import { CallAction } from '../components/CallAction'

export const RentalListPage = () => {

  return (
    <>

        <div id ="atalho" className="container-xxl py-5">
            <div className="container">
                <div className="row g-0 gx-5 align-items-end">
                    <div className="col-lg-6">
                        <div className="text-start mx-auto mb-5 wow slideInLeft" data-wow-delay="0.1s">
                            <h1 className="mb-3">Imoveis Disponíveis</h1>
                            <p>Explore nossa seleção de imóveis disponíveis para aluguel e encontre o lar perfeito para você. Cada opção é cuidadosamente selecionada para atender às suas necessidades e estilo de vida.</p>
                        </div>
                    </div>
                </div>
                <div className="tab-content">
                    <div id="property-list" className="row g-4">
                       <RentalList/>
                    </div>
                    <div className="col-12 text-center">
                        <a className="btn btn-primary py-3 px-5" href="property-list.html">Mostrar mais imoveis</a>
                    </div>
                </div>
            </div>
        </div>
        <CallAction/>
    </>
  )
}
