// frontend/src/pages/Login.jsx
import React from 'react';
import { useForm } from 'react-hook-form';
import { Link } from 'react-router';
import { useAuth } from '../auth/authContext';

export const Login = () => {
  const { register, handleSubmit, formState: { errors }, reset } = useForm();
  const { login } = useAuth()
  const onSubmit = async (data) => {
    const { error } =  await login(data)
    if (error) window.alert("usuario ou senha errados")
    reset()
  };

  return (
    <div className="container-xxl py-5">
      <div className="container">
        <div className="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style={{ maxWidth: '600px' }}>
          <h1 className="mb-3">Login</h1>
          <p>Faça login para acessar sua conta.</p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="wow fadeInUp" data-wow-delay="0.3s">
          <div className="row g-3">
            {/* E-mail */}
            <div className="col-md-12">
              <div className="form-floating">
                <input
                  type="email"
                  className={`form-control ${errors.email ? 'is-invalid' : ''}`}
                  id="email"
                  placeholder="E-mail"
                  {...register('email', { required: 'E-mail é obrigatório' })}
                />
                <label htmlFor="email">E-mail</label>
                {errors.email && (
                  <div className="invalid-feedback">{errors.email.message}</div>
                )}
              </div>
            </div>

            {/* Senha */}
            <div className="col-md-12">
              <div className="form-floating">
                <input
                  type="password"
                  className={`form-control ${errors.password ? 'is-invalid' : ''}`}
                  id="password"
                  placeholder="Senha"
                  {...register('password', { required: 'Senha é obrigatória' })}
                />
                <label htmlFor="password">Senha</label>
                {errors.password && (
                  <div className="invalid-feedback">{errors.password.message}</div>
                )}
              </div>
            </div>

            {/* Botão de Envio */}
            <div className="col-12">
              <button className="btn btn-primary w-100 py-3" type="submit">
                Entrar
              </button>
            </div>

            {/* Link para Cadastro */}
            <div className="col-12 text-center">
              <p className="mb-0">
                Não tem uma conta? <Link to="/singup">Cadastre-se</Link>
              </p>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};

// mab-rental/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { CommonModule, NgClass } from '@angular/common';

@Component({
  selector: 'app-login',
  // SINTAXE MODERNA
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink, NgClass], // Adicionamos as importações necessárias
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;
  isSubmitting: boolean = false;

  constructor(private fb: FormBuilder, private router: Router) {}

  ngOnInit(): void {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required]
    });
  }

  get f() {
    return this.loginForm.controls;
  }

  async mockLogin(data: any): Promise<{ error?: string }> {
    console.log('Tentativa de login com:', data);
    if (data.email === 'user@test.com' && data.password === '123456') {
      return {};
    } else {
      return { error: 'usuario ou senha errados' };
    }
  }

  async onSubmit(): Promise<void> {
    this.isSubmitting = true;

    if (this.loginForm.invalid) {
      this.loginForm.markAllAsTouched();
      this.isSubmitting = false;
      return;
    }

    const data = this.loginForm.value;
    const { error } = await this.mockLogin(data);
    
    if (error) {
      window.alert('Usuário ou senha errados');
      this.loginForm.reset();
    } else {
      this.router.navigate(['/']);
    }

    this.isSubmitting = false;
  }
}
<div class="py-12">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div class="text-center mx-auto mb-8" style="max-width: 600px;">
            <h1 class="text-3xl sm:text-4xl font-bold mb-3 text-gray-800">Login</h1>
            <p class="text-gray-600">Faça login para acessar sua conta.</p>
        </div>

        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="mx-auto max-w-lg bg-white p-8 rounded-xl shadow-2xl">
            <div class="grid gap-6">
                
                <div class="col-span-full relative">
                    <input
                        type="email"
                        formControlName="email"
                        id="email"
                        placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{
                            'border-red-500 focus:ring-red-500': f['email'].invalid && (f['email'].dirty || f['email'].touched)
                        }"
                    />
                    <label 
                        htmlFor="email" 
                        class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm"
                    >
                        E-mail
                    </label>
                    
                    <div *ngIf="f['email'].invalid && (f['email'].dirty || f['email'].touched)" class="mt-1 text-sm text-red-500">
                        <p *ngIf="f['email'].errors?.['required']">E-mail é obrigatório</p>
                        <p *ngIf="f['email'].errors?.['email']">E-mail inválido</p>
                    </div>
                </div>

                <div class="col-span-full relative">
                    <input
                        type="password"
                        formControlName="password"
                        id="password"
                        placeholder=" "
                        class="w-full h-12 px-4 border border-gray-300 rounded-lg text-gray-900 placeholder-transparent focus:outline-none focus:ring-2 focus:ring-blue-600 peer"
                        [ngClass]="{
                            'border-red-500 focus:ring-red-500': f['password'].invalid && (f['password'].dirty || f['password'].touched)
                        }"
                    />
                    <label 
                        htmlFor="password" 
                        class="absolute left-4 -top-3.5 text-gray-600 text-sm bg-white px-1 transition-all peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400 peer-placeholder-shown:top-3 peer-focus:-top-3.5 peer-focus:text-blue-600 peer-focus:text-sm"
                    >
                        Senha
                    </label>

                    <div *ngIf="f['password'].invalid && (f['password'].dirty || f['password'].touched)" class="mt-1 text-sm text-red-500">
                        <p *ngIf="f['password'].errors?.['required']">Senha é obrigatória</p>
                    </div>
                </div>

                <div class="col-span-full">
                    <button 
                        type="submit" 
                        [disabled]="loginForm.invalid || isSubmitting"
                        class="w-full bg-blue-600 text-white font-semibold py-3 rounded-lg hover:bg-blue-700 transition duration-300 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {{ isSubmitting ? 'Entrando...' : 'Entrar' }}
                    </button>
                </div>

                <div class="col-span-full text-center mt-2">
                    <p class="text-gray-600">
                        Não tem uma conta? 
                        <a routerLink="/singup" class="text-blue-600 hover:text-blue-800 font-medium">Cadastre-se</a>
                    </p>
                </div>
            </div>
        </form>
    </div>
</div>
